# Generated by Django 4.2.27 on 2026-01-15 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eveuniverse', '0011_extend_industry_activites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eveonline', '0017_alliance_and_corp_names_are_not_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('basic_access', 'Can access this app'), ('admin_access', 'Can set tax rates for groups and add accountant characters'), ('auditor_access', 'Can view all registered characters data')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AdminCharacter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvetaxes_admins', to='eveonline.evecorporationinfo')),
                ('eve_character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pvetaxes_admin', to='eveonline.evecharacter')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('life_credits', models.FloatField(default=0.0)),
                ('life_taxes', models.FloatField(default=0.0)),
                ('monthly_activity_json', models.JSONField(blank=True, default=dict, null=True)),
                ('monthly_taxes_json', models.JSONField(blank=True, default=dict, null=True)),
                ('monthly_credits_json', models.JSONField(blank=True, default=dict, null=True)),
                ('last_wallet_update', models.DateTimeField(blank=True, null=True)),
                ('eve_character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pvetaxes_character', to='eveonline.evecharacter')),
            ],
            options={
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate', models.FloatField(default=0.0, help_text='Monthly interest rate applied to outstanding balances (as decimal, e.g., 0.05 for 5%)')),
                ('phrase', models.CharField(blank=True, help_text='Phrase to search for in corp wallet journal to identify tax payments', max_length=255)),
                ('discord_webhook_url', models.CharField(blank=True, help_text='Discord webhook URL for public notifications', max_length=500)),
                ('discord_bot_token', models.CharField(blank=True, help_text='Discord bot token for sending DMs', max_length=200)),
                ('discord_send_individual_dms', models.BooleanField(default=False, help_text='Send individual Discord DMs to users about their taxes')),
                ('discord_send_corp_summary', models.BooleanField(default=False, help_text='Send a corp-wide summary of outstanding taxes to Discord')),
                ('last_interest_applied', models.DateTimeField(blank=True, help_text='Last time interest was applied to outstanding balances', null=True)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curmonth_bounties', models.FloatField(default=0.0)),
                ('curmonth_ess', models.FloatField(default=0.0)),
                ('curmonth_missions', models.FloatField(default=0.0)),
                ('curmonth_incursions', models.FloatField(default=0.0)),
                ('curmonth_bounties_tax', models.FloatField(default=0.0)),
                ('curmonth_ess_tax', models.FloatField(default=0.0)),
                ('curmonth_missions_tax', models.FloatField(default=0.0)),
                ('curmonth_incursions_tax', models.FloatField(default=0.0)),
                ('life_bounties', models.FloatField(default=0.0)),
                ('life_ess', models.FloatField(default=0.0)),
                ('life_missions', models.FloatField(default=0.0)),
                ('life_incursions', models.FloatField(default=0.0)),
                ('life_bounties_tax', models.FloatField(default=0.0)),
                ('life_ess_tax', models.FloatField(default=0.0)),
                ('life_missions_tax', models.FloatField(default=0.0)),
                ('life_incursions_tax', models.FloatField(default=0.0)),
                ('curmonth_leadergraph', models.JSONField(blank=True, default=dict)),
                ('user_activity_ledger_90day', models.JSONField(blank=True, default=dict)),
                ('admin_get_all_activity_json', models.JSONField(blank=True, default=dict)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statistics',
                'verbose_name_plural': 'Statistics',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CharacterTaxCredits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('credit_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('payment', 'Payment'), ('interest', 'Interest'), ('adjustment', 'Adjustment')], default='credit', max_length=20)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_credits', to='pvetaxes.character')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CharacterWalletJournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_id', models.BigIntegerField(db_index=True, unique=True)),
                ('date', models.DateTimeField(db_index=True)),
                ('amount', models.FloatField()),
                ('ref_type', models.CharField(max_length=100)),
                ('activity_type', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('tax_amount', models.FloatField(default=0.0)),
                ('tax_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_journal', to='pvetaxes.character')),
                ('eve_solar_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eveuniverse.evesolarsystem')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['character', 'date'], name='pvetaxes_ch_charact_6c5b03_idx'), models.Index(fields=['activity_type', 'date'], name='pvetaxes_ch_activit_ba3c9e_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminCorpWalletEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_id', models.BigIntegerField(db_index=True, unique=True)),
                ('date', models.DateTimeField(db_index=True)),
                ('amount', models.FloatField()),
                ('second_party_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corp_wallet_entries', to='pvetaxes.admincharacter')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['admin_character', 'date'], name='pvetaxes_ad_admin_c_4287f6_idx')],
            },
        ),
    ]
